- name: 시스템 업데이트
  apt:
    update_cache: yes
    upgrade: yes

- name: 스왑 비활성화
  shell: |
    swapoff -a
    sed -i '/\bswap\b/ s/^/#/' /etc/fstab

- name: 커널 모듈 설정
  shell: |
    modprobe overlay
    modprobe br_netfilter
    cat <<EOF | tee /etc/modules-load.d/k8s.conf >/dev/null
    overlay
    br_netfilter
    EOF
    cat <<EOF | tee /etc/sysctl.d/k8s.conf >/dev/null
    net.bridge.bridge-nf-call-iptables=1
    net.bridge.bridge-nf-call-ip6tables=1
    net.ipv4.ip_forward=1
    EOF
    sysctl --system

- name: containerd 설치
  apt:
    name: containerd
    state: present

- name: containerd 기본 설정
  shell: |
    mkdir -p /etc/containerd
    containerd config default | tee /etc/containerd/config.toml >/dev/null
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
    systemctl enable containerd
    systemctl restart containerd

- name: Kubernetes 패키지 저장소 추가
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key \
      | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] \
      https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" \
      | tee /etc/apt/sources.list.d/kubernetes.list
    apt-get update -y
  args:
    executable: /bin/bash


- name: kubeadm, kubelet, kubectl 설치
  apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
  notify: enable services

- name: kubeadm, kubelet, kubectl 버전 고정
  command: apt-mark hold kubeadm kubelet kubectl

- name: UFW 방화벽 허용
  shell: |
    ufw allow 6443
    ufw allow 2379
    ufw allow 2380
    ufw allow 10250
    ufw allow 10251
    ufw allow 10252
    ufw allow 8285
    ufw allow 8472
    ufw --force enable
  ignore_errors: true
